import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL ?? "https://rnnp.lv"),
  title: {
    default: "RNNP | Horizontālā urbšana un pazemes kabeļu trases",
    template: "%s | RNNP",
  },
  description:
    "RNNP piedāvā horizontālās urbšanas, beztranšeju cauruļvadu, kabeļu līniju un pazemes elektrokabeļu trašu pakalpojumus Latvijā.",
  applicationName: "RNNP",
  authors: [{ name: "RNNP" }],
  creator: "RNNP",
  publisher: "RNNP",
  verification: {
    google: "yGuvGlncY9DoIcDUeWZnNnYVuOtiP3-cIZHTYRLTgUU",
  },
  icons: {
    icon: "/icon.png",
    shortcut: "/icon.png",
    apple: "/icon.png",
  },
  alternates: {
    canonical: "/",
    languages: {
      "lv-LV": "/",
      "ru-LV": "/ru",
      "x-default": "/",
    },
  },
  keywords: [
    "horizontālā urbšana",
    "horizontāli vadāmā urbšana",
    "horizontālā urbšana Latvijā",
    "horizontala urbsana",
    "horizontala urbsana latvija",
    "horizontali vadama urbsana",
    "horizontali vadama urbsana latvija",
    "horizontālā urbšana Rīga",
    "horizontālā urbšana Pierīga",
    "horizontālā urbšana Bauska",
    "horizontālā urbšana Zemgale",
    "HDD urbšana Latvijā",
    "HDD urbšana",
    "HDD drilling Latvia",
    "horizontal directional drilling Latvia",
    "directional drilling Latvia",
    "trenchless drilling Latvia",
    "beztranšeju urbšana",
    "beztranšeju metode",
    "beztranšeju cauruļvadi",
    "bez tranšejas",
    "beztranseju urbsana",
    "beztranseju metode",
    "beztranseju komunikacijas",
    "beztranšeju komunikācijas",
    "beztranšeju darbi",
    "beztranšeju izbūve",
    "komunikāciju izbūve",
    "komunikaciju izbuve",
    "komunikāciju izbūve Latvijā",
    "komunikaciju izbuve Latvija",
    "komunikāciju izbūve bez tranšejas",
    "komunikaciju izbuve bez transejas",
    "pazemes komunikāciju izbūve",
    "pazemes komunikaciju izbuve",
    "ārējo komunikāciju izbūve",
    "arejo komunikaciju izbuve",
    "inženiertīklu izbūve",
    "inzeniertiklu izbuve",
    "inženiertīklu ierīkošana",
    "inzeniertiklu ierikosana",
    "komunikāciju ierīkošana",
    "komunikaciju ierikosana",
    "komunikāciju pieslēgumi",
    "komunikaciju pieslegumi",
    "pieslēgumu izbūve",
    "pieslegumu izbuve",
    "privātmājas komunikāciju izbūve",
    "privatmajas komunikaciju izbuve",
    "komunikāciju izbūve uzņēmumiem",
    "komunikaciju izbuve uznemumiem",
    "komunikāciju izbūve objektiem",
    "komunikaciju izbuve objektiem",
    "inženierkomunikāciju izbūve",
    "inzenierkomunikaciju izbuve",
    "inženierkomunikācijas",
    "inzenierkomunikacijas",
    "inženierkomunikāciju izbūve Latvijā",
    "cauruļu ievilkšana zem ceļa",
    "caurules ievilksana zem cela",
    "caurules zem ceļa",
    "caurules zem cela",
    "cauruļu ievilkšana",
    "caurulu ievilksana",
    "kabeļu ievilkšana zem ceļa",
    "kabela ievilksana zem cela",
    "kabeļu ievilkšana",
    "kabelu ievilksana",
    "cauruļvadu ierīkošana",
    "caurulvadu ierikosana",
    "aizsargcauruļu ievilkšana",
    "aizsargcaurulu ievilksana",
    "aizsargcaurules kabeļiem",
    "aizsargcaurules kabeliem",
    "kabeļu līniju izbūve",
    "kabelu liniju izbuve",
    "inženierkomunikāciju izbūve",
    "ūdensvada pieslēgums",
    "udensvada pieslegums",
    "ūdensvada ievilkšana",
    "udensvada ievilksana",
    "kanalizācijas pieslēgums",
    "kanalizacijas pieslegums",
    "kanalizācijas caurules ievilkšana",
    "kanalizacijas caurules ievilksana",
    "elektrības kabeļu izbūve",
    "elektribas kabelu izbuve",
    "sakaru kabeļu izbūve",
    "sakaru kabelu izbuve",
    "elektrokabeļu trases",
    "elektrokabelu trases",
    "pazemes kabeļu izbūve",
    "pazemes kabelu izbuve",
    "pazemes kabeļu ievilkšana",
    "pazemes kabelu ievilksana",
    "elektroapgādes pieslēgumi",
    "elektroapgades pieslegumi",
    "elektropieslēguma izbūve",
    "elektropiesleguma izbuve",
    "kabeļu trases saules parkiem",
    "kabelu trases saules parkiem",
    "elektrokabeļu izbūve saules paneļiem",
    "elektrokabeļu izbūve saules parkam",
    "elektrokabelu izbuve saules parkam",
    "pazemes kabeļi saules paneļu parkiem",
    "pazemes kabeli saules panelu parkiem",
    "saules parka elektrokabeļi",
    "saules parka elektrokabeli",
    "saules paneļu parka kabeļu trases",
    "saules panelu parka kabelu trases",
    "pazemes kabeļi vēja parkiem",
    "pazemes kabeli veja parkiem",
    "vēja parku elektrokabeļi",
    "veja parku elektrokabeli",
    "vēja enerģijas objektu kabeļu trases",
    "veja energijas objektu kabelu trases",
    "vēja parka kabeļu trases",
    "veja parka kabelu trases",
    "elektropieslēgums saules parkam",
    "komunikāciju ievilkšana zem ceļa",
    "komunikaciju ievilksana zem cela",
    "urbums zem ceļa",
    "urbums zem cela",
    "urbšana zem ceļa",
    "urbsana zem cela",
    "caurdure zem ceļa",
    "caurdure zem cela",
    "prokols zem ceļa",
    "prokols zem cela",
    "горизонтальное бурение",
    "горизонтально направленное бурение",
    "горизонтально направленное бурение Латвия",
    "горизонтальное бурение Бауска",
    "горизонтальное бурение Земгале",
    "ГНБ Латвия",
    "ГНБ Рига",
    "ГНБ Бауска",
    "ГНБ Земгале",
    "gnb latvia",
    "gnb riga",
    "hdd latvia",
    "hdd drilling latvia",
    "прокол под дорогой",
    "прокол под дорогой Латвия",
    "прокол под дорогой Рига",
    "прокол дороги",
    "прокол под асфальтом",
    "прокол под тротуаром",
    "прокол под двором",
    "прокол под дорогой цена",
    "прокол под дорогой стоимость",
    "prokol pod dorogoj",
    "prokol pod dorogoy",
    "prokol latvia",
    "prokol riga",
    "бестраншейная прокладка труб",
    "бестраншейное бурение",
    "бестраншейные коммуникации",
    "бестраншейная прокладка коммуникаций",
    "прокладка инженерных коммуникаций",
    "строительство инженерных коммуникаций",
    "подземные инженерные коммуникации",
    "наружные инженерные коммуникации",
    "инженерные сети Латвия",
    "прокладка инженерных сетей",
    "подключение инженерных коммуникаций",
    "коммуникации для ��астного дома",
    "коммуникации для предприятий",
    "бестраншейные работы",
    "прокладка коммуникаций без траншеи",
    "прокладка труб без траншеи",
    "протяжка трубы под дорогой",
    "протяжка трубы под землей",
    "прокладка кабеля под землей",
    "подземная прокладка кабеля",
    "подземные кабельные трассы",
    "протяжка кабеля под дорогой",
    "прокладка электрического кабеля под землей",
    "прокладка силового кабеля под землей",
    "прокладка кабельных линий",
    "защитные трубы для кабеля",
    "защитная труба для кабеля",
    "футляр под кабель",
    "труба футляр под дорогой",
    "прокладка водопровода",
    "прокладка водопровода под дорогой",
    "подключение водопровода",
    "прокладка канализации",
    "прокладка канализации под дорогой",
    "подключение канализации",
    "кабельные трассы для солнечных парков",
    "прокладка кабеля для солнечных панелей",
    "подземные кабели для солнечных парков",
    "кабельные трассы для ветропарков",
    "подземные кабели для ветропарков",
    "кабельные линии для ветроэнергетики",
    "электроподключение ветропарка",
    "солнечный парк кабельные трассы",
    "кабель для солнечной электростанции",
    "ветропарк кабельные трассы",
    "прокладка кабеля для ветропарка",
    "электроподключение солнечного парка",
    "инженерные коммуникации Латвия",
    "горизонтальное бурение Рига",
    "бурение под дорогой Латвия",
    "underground cable installation Latvia",
    "underground utilities Latvia",
    "trenchless utilities Latvia",
    "solar park cable installation Latvia",
    "wind park cable installation Latvia",
    "RNNP",
  ],
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "lv_LV",
    alternateLocale: ["ru_LV"],
    url: "/",
    siteName: "RNNP",
    title: "RNNP | Horizontālā urbšana un pazemes kabeļu trases",
    description:
      "Horizontālās urbšanas, beztranšeju inženierkomunikāciju izbūves un pazemes elektrokabeļu trašu pakalpojumi Latvijā.",
  },
  twitter: {
    card: "summary_large_image",
    title: "RNNP | Horizontālā urbšana un kabeļu trases",
    description:
      "Beztranšeju cauruļvadu, kabeļu līniju un pazemes elektrokabeļu trašu ierīkošana Latvijā.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="lv" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        {children}
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
